antvis/gatsby-theme-antv

.gitignore
@antv/gatsby-theme-antv/package.json
@antv/gatsby-theme-antv/site/components/Header.tsx
@antv/gatsby-theme-antv/site/components/withProvider.tsx

增加 i18n provider
ChartCube 这种只引入 Header Footer的 需要用 withProvider包装一下
```js
import LHeader from '@antv/gatsby-theme-antv/lib/components/Header';
import LFooter from '@antv/gatsby-theme-antv/lib/components/Footer';
import withProivder from '@antv/gatsby-theme-antv/lib/components/withProvider';
const Header = withProivder(LHeader);
const Footer = withProivder(LFooter);
```

feat: 增加i18n provider

---

@antv/gatsby-theme-antv/README.md
@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/components/Footer.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
README.md
example/gatsby-config.js

https://github.com/antvis/antvis.github.io/issues/18#issuecomment-552097061

feat: support redirects

---

.eslintrc
@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/package.json
@antv/gatsby-theme-antv/site/common.json
@antv/gatsby-theme-antv/site/components/Header.module.less
@antv/gatsby-theme-antv/site/components/PlayGround.tsx
@antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
@antv/gatsby-theme-antv/site/components/Toolbar.module.less
@antv/gatsby-theme-antv/site/components/Toolbar.tsx
@antv/gatsby-theme-antv/site/global.less
@antv/gatsby-theme-antv/site/templates/example.tsx
example/gatsby-config.js
yarn.lock

close #74
antvis/G2#1725
需要修改 `gatsby-config.js`: https://github.com/antvis/gatsby-theme-antv/blob/8585ccf72fdbc98da987e2a83c8abd77b599fa46/example/gatsby-config.js#L87-L101

feat: ⚡️ support html source code of examples

---

.eslintignore
@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/common.json
@antv/gatsby-theme-antv/site/components/Header.module.less
@antv/gatsby-theme-antv/site/components/Header.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
README.md
example/gatsby-config.js
example/package.json

feat: versions select

---

@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
@antv/gatsby-theme-antv/site/templates/example.tsx
@antv/gatsby-theme-antv/site/templates/markdown.module.less
example/examples/basic/index.en.md
example/examples/basic/index.zh.md
example/examples/gallary/index.en.md
example/examples/gallary/index.zh.md
example/gatsby-config.js

演示支持所有图表页面（Gallary）。
添加办法如下：
1. 升级 `@antv/gatsby-theme-antv` 到 `0.10.26` 版本以上。
2. 在 `examples` 目录下添加 gallary 文件夹和两个 md 文件，内容照抄[这里](https://github.com/antvis/gatsby-theme-antv/tree/683f43c13110782f3e65c199a3bc9bef22c343f3/example/examples/gallary)。
3. 修改顶部导航的链接 `slug` 为 `examples/gallary`，去除演示里相关的 `redirect_from` 属性：https://github.com/antvis/gatsby-theme-antv/commit/5f13ce74287ba435b9b8cae65b00d32527e4d55f
有问题请联系 @afc163

feat: Charts Gallary of examples

---

.github/workflows/nodejs.yml
@antv/gatsby-theme-antv/package.json
@antv/gatsby-theme-antv/site/templates/example.tsx
yarn.lock

```
ERROR #85901  GRAPHQL
There was an error in your GraphQL query:
Expected node, not `[object Object]`
17 |         playgroundWillUnmount
18 |         dependencies
19 |         htmlCodeTemplate
20 |       }
21 |     }
22 |     pathPrefix
23 |   }
24 |   allMarkdownRemark(filter: {fields: {slug: {regex: "//examples//"}}}, sort: {order: ASC, fields: [frontmatter___order]}, limit: 1000) {
```
原因是 https://github.com/gatsbyjs/gatsby/pull/21188#issuecomment-617698871 ，先锁版本修复。

fix: site build throw error

---

@antv/gatsby-theme-antv/site/components/PlayGround.tsx

The URL of the fetch is the online address, and you can still view the data

feat: support display data with http request in demo

---

@antv/gatsby-theme-antv/site/components/Tabs.module.less
@antv/gatsby-theme-antv/site/components/Tabs.tsx
@antv/gatsby-theme-antv/site/templates/example.tsx

fix: improve docsearch result

---

@antv/gatsby-theme-antv/site/components/Footer.module.less
@antv/gatsby-theme-antv/site/components/Footer.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
@antv/gatsby-theme-antv/site/pages/404.tsx
@antv/gatsby-theme-antv/site/templates/document.tsx
@antv/gatsby-theme-antv/site/templates/example.tsx
@antv/gatsby-theme-antv/site/templates/markdown.module.less

* widen tabOfContent from 160px to 204 px referrence to yuque UI;
* tabOfContent ellipsis text;
* make menu can scroll when it over 100vh;
* footer not to be cover;

fix issue of document template menu and tabOfContent

---

@antv/gatsby-theme-antv/package.json
@antv/gatsby-theme-antv/site/components/APIDoc.tsx
@antv/gatsby-theme-antv/site/components/Banner.tsx
@antv/gatsby-theme-antv/site/components/CodeLoading.tsx
@antv/gatsby-theme-antv/site/components/Footer.tsx

AntV 系列官网首页有一个推广链接列表，目前依赖各站点手动维护，需要重新部署才能生效，批量修改的效率很低。
现在通过 https://my-json-server.typicode.com/ 服务建了一个免费简单的 Headless CMS，数据放在单独的仓库 https://github.com/antvis/antvis-sites-data ，后续需要修改直接在线修改 [db.json](https://github.com/antvis/antvis-sites-data/edit/main/db.json) 即可，提交即生效。
AntV 系列站点若未定义 Banner 的 notifications，会默认取这里的数据，否则走自定义的数据。这样统一修改 AntV 所有站点的通知内容会很方便。
可用数据接口请查看：https://my-json-server.typicode.com/antvis/antvis-sites-data
---
antd 也有类似的需求：https://github.com/ant-design/ant-design/issues/27389

feat: Read news from My JSON Server

---

@antv/gatsby-theme-antv/site/templates/markdown.module.less

style: markdown 中的 ul ol 样式不对

---

@antv/gatsby-theme-antv/site/templates/markdown.module.less

for better contrast
---
新版字体有点淡，不适于阅读。

style: revert markdown text color

---

@antv/gatsby-theme-antv/site/templates/markdown.module.less

对于这种文字比较短的是硬伤，视觉不平衡
改一下看起来舒服
再看看 G6 的
修改后

gallery 页面图片和文字居中对齐，清一色居左对齐看起来好累

---

@antv/gatsby-theme-antv/site/layouts/layout.module.less
@antv/gatsby-theme-antv/site/templates/markdown.module.less

| before ❌ | after ✔️ |
| --- | --- |
| <img width="497" alt="图片" src="https://user-images.githubusercontent.com/507615/105950972-4dbef880-60aa-11eb-87c8-430ef4539089.png"> | <img width="498" alt="图片" src="https://user-images.githubusercontent.com/507615/105951174-98d90b80-60aa-11eb-894e-1667dc16b769.png"> |
这段代码在 https://github.com/antvis/gatsby-theme-antv/commit/058cd75524b43bf081ed1f1016c91bdf28cf308f#diff-c7e14ccebbf9f624feeb0d3e4dd7601c4e768879c2e60a5f0c8f9fb45374eb94R223 里加的。

fix: side menu broder style

---

@antv/gatsby-theme-antv/gatsby-config.js
@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/templates/example.tsx
README.md
example/gatsby-config.js

针对 g2 g2plot 等站点 demo 较多的站点新增配置项，允许进入 gallery 页面是否默认收起所有 sub menu，默认全部展开

feat: gallery menu open default status able config

---

@antv/gatsby-theme-antv/site/components/APIDoc.tsx
@antv/gatsby-theme-antv/site/components/MdPlayground.tsx
example/api-extractor.json
example/docs/api/g2plot/scatter.en.md
example/docs/api/g2plot/scatter.zh.md
example/gatsby-config.js
package.json

之前加的配置，可以设置宽度 50%，如下（不生效）
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/112998787-f409a600-91a0-11eb-8ef8-841a20522310.png)|![image](https://user-images.githubusercontent.com/15646325/112998679-da685e80-91a0-11eb-9f1d-13a5fad975f8.png)|

fix: 修复 md playground 设置宽度不生效 & 版本锁定解决playground无法运作

---

@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/common.json
@antv/gatsby-theme-antv/site/components/Contributors.module.less
@antv/gatsby-theme-antv/site/components/Contributors.tsx
@antv/gatsby-theme-antv/site/templates/document.tsx
@antv/gatsby-theme-antv/site/templates/markdown.module.less
example/docs/api/g2plot/scatter.en.md
example/docs/api/g2plot/scatter.zh.md

如 pr 实例的 scatter 文档所示，可以添加文档贡献者信息。效果如下：
| 英文文档 | 中文文档 |
| --- | --- |
|![image](https://user-images.githubusercontent.com/15646325/113002418-557f4400-91a4-11eb-8cc9-744a3f950af3.png)|![image](https://user-images.githubusercontent.com/15646325/113002517-6fb92200-91a4-11eb-8bcb-ba6746a85aac.png)|

feat(docs-contributors): 文档添加贡献者信息

---

@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/components/Header.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
example/gatsby-config.js

背景：头部平铺菜单项太多，需要收拢（暂时收口到【周边生态】里边）
| 配置方式 | 效果 |
| --- | --- |
|![image](https://user-images.githubusercontent.com/15646325/113805414-126c3480-9793-11eb-888c-c338a8b95b29.png)| ![image](https://user-images.githubusercontent.com/15646325/113805389-07b19f80-9793-11eb-867c-4f9f976498c7.png)|

feat: header 增加下拉菜单，可以存放一些生态的外链

---

@antv/gatsby-theme-antv/site/components/TopBanner.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
@antv/gatsby-theme-antv/site/templates/example.tsx
example/examples/radar/basic/demo/meta.json

| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/15646325/119375503-74560e80-bced-11eb-8885-0e7495117309.png), ![image](https://user-images.githubusercontent.com/15646325/119375529-7cae4980-bced-11eb-8de4-9d723c90d5a8.png)| ![image](https://user-images.githubusercontent.com/15646325/119377027-378b1700-bcef-11eb-9ee9-a70b4fb49300.png), ![image](https://user-images.githubusercontent.com/15646325/119377060-41147f00-bcef-11eb-99a1-4b08fdc229ba.png) |

fix(announcement): 公告判空不展示

---

@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/site/components/PlayGround.tsx
@antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
@antv/gatsby-theme-antv/site/templates/example.tsx

fix:  去除page中传递的posts 修改跨二级菜单的跳转方法

---

@antv/gatsby-theme-antv/site/components/PlayGround.tsx
@antv/gatsby-theme-antv/site/components/PlayGrounds.tsx

fix: 修复SplitPane 组件在缺少子元素的时候 size更新失效的问题 修复动画示例对于SplitPane Scroll沉底的问题 重新添加回二级菜单更新跳转

---

@antv/gatsby-theme-antv/site/components/APIDoc.module.less

fix: 修复抽屉样式

---

@antv/gatsby-theme-antv/package.json

`react` 和 `react-dom` 应该放在 `peerDependencies`, 不然导致一个项目有两个 `react` 版本

chore: move `react` and `react-dom` to `peerDependencies`

---

@antv/gatsby-theme-antv/site/components/PlayGround.tsx

修复跳转匹配问题 
https://github.com/antvis/G2Plot/issues/3057

fix(playGround): 修复跳转匹配问题

---

package.json

在 `M1` 的 `mac` 环境下使用 `yarn install` 会报错，提示  `sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8`
查看 [sharp官网关于M1芯片的说明](https://sharp.pixelplumbing.com/install#apple-m1) 后得知，`0.29.x` 版本才支持 `ARM64`
查看当前sharp版本
```bash
npm list sharp
@antv/gatsby-theme-antv@ /Users/shiyu/DCODE/gatsby-theme-antv
└─┬ @antv/gatsby-theme-antv@1.1.16 -> ./@antv/gatsby-theme-antv
└─┬ gatsby-plugin-manifest@2.12.1
└── sharp@0.27.2
```
`gatsby-theme-antv` 依赖 `gatsby-plugin-manifest`的第二个大版本，其中依赖的sharp被锁定在 `0.27.x`
在 `package.json` 中，利用 `resolutions` 字段，将 `sharp` 版本锁定在 `0.29.x` 以上

fix: 修复 arm 芯片下 npm 安装 sharp 报错的问题

---

@antv/gatsby-theme-antv/site/templates/document.tsx
@antv/gatsby-theme-antv/site/templates/markdown.module.less

Fixes an issue where the generated table of contents will overlap the footer when the page is scrolled to the bottom, as can be seen in antvis/X6#1940.
This uses a plain `div` with `position: sticky` instead of the `Affix` component.
Before:
https://user-images.githubusercontent.com/93302820/160517847-9a04b501-c867-4f3e-8c89-4550bc49bdaf.mov
After:
https://user-images.githubusercontent.com/93302820/160517860-bcdef26f-f66f-4539-b20a-1abe2caae97b.mov

fix: page ToC overflowing into footer

---

@antv/gatsby-theme-antv/gatsby-browser.js
@antv/gatsby-theme-antv/gatsby-node.js
@antv/gatsby-theme-antv/package.json
@antv/gatsby-theme-antv/site/components/Search.module.less
@antv/gatsby-theme-antv/site/components/Search.tsx
@antv/gatsby-theme-antv/site/layouts/layout.tsx
README.md

新申请的 docsearch key包含 appId, 只适用于 v3.x 版本的docsearch.js, v2.x  版本 appId 可不填默认提供写死
详情见 https://docsearch.algolia.com/
考虑到整栈升级成本，提供两种版本的组件配置选项，效果如下：
v2.x:
v3.x
（PS: 样式就这样叭，随便改改，摆烂了，又不是不能用🙃🙃🙃🙃）

feat: 新增v3.x版本docsearch适配新申请的子站点

---

@antv/gatsby-theme-antv/site/components/PlayGround.tsx

问题的来源是G2Plot关于双轴图的一个demo链接打开错误
点击demo会跳转到https://g2plot.antv.vision/zh/examples/dual-axes/dual-line
这个链接打开, 理论上应该是打开双轴图的, 实际打开的却是面积图. 对比了下其他的demo链接, 发现是少了哈希路由参数
正确的应该是https://g2plot.antv.vision/zh/examples/dual-axes/dual-line#dual-line
本来是想修改文档链接的, 但是我发现这种不带哈希的路由有好多地方在使用, 不止是G2Plot, 很多antv系列产品都在使用. 我怀疑最早的时候是支持不带哈希路由的, 不带哈希路由的情况下, 应该是默认读取这个类别的第一个demo才是. 而不是随便找个图表类型.

fix: fix default demo error
