- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/PlayGround.module.less
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- @antv/gatsby-theme-antv/site/global.less
- yarn.lock
https://github.com/tomkp/react-split-pane
> feat: Add react-split-pane

- @antv/gatsby-theme-antv/gatsby-browser.js
- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- example/examples/basic/demo/basic.js
- yarn.lock
https://github.com/antvis/g2/pull/1607#issuecomment-550586978
```diff
import G2 from '@antv/g2';
+ import insertCss from 'insert-css';
+ insertCss(`
+   .custom { background: blue; }
+ `);
const data = [
{ genre: 'Sports', sold: 275 },
{ genre: 'Strategy', sold: 1150 },
{ genre: 'Action', sold: 120 },
{ genre: 'Shooter', sold: 350 },
{ genre: 'Other', sold: 150 },
];
const chart = new G2.Chart({
container: document.getElementById('container'),
width: 500,
height: 500,
});
chart.source(data);
chart
.interval()
.position('genre*sold')
.color('genre');
chart.render();
```
> feat: support insert css in example code

- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Features.module.less
- @antv/gatsby-theme-antv/site/components/Footer.tsx
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
- @antv/gatsby-theme-antv/site/components/Product.module.less
- @antv/gatsby-theme-antv/site/components/Product.tsx
- @antv/gatsby-theme-antv/site/components/Products.tsx
- @antv/gatsby-theme-antv/site/components/Search.module.less
- @antv/gatsby-theme-antv/site/components/getProducts.ts
- @antv/gatsby-theme-antv/site/pages/index.tsx
- README.md
- example/site/pages/index.zh.tsx
> feat: Header and Products card

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/site/components/Features.tsx
- @antv/gatsby-theme-antv/site/components/NavigatorBanner.module.less
- @antv/gatsby-theme-antv/site/components/NavigatorBanner.tsx
- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
- example/examples/category/second/index.zh.md
> feat: add prev and next article buttons

- @antv/gatsby-theme-antv/gatsby-browser.js
- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
- yarn.lock
> feat: Add doc menu in drawer

- @antv/gatsby-theme-antv/site/components/Footer.tsx
> feat: 🇨🇳 open notification for china mirror

- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
- yarn.lock
> fix: mobile menu

- @antv/gatsby-theme-antv/externals.d.ts
- @antv/gatsby-theme-antv/gatsby-browser.js
- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/NavMenuItems.tsx
- @antv/gatsby-theme-antv/site/components/ReadingTime.tsx
- @antv/gatsby-theme-antv/site/components/Search.module.less
- @antv/gatsby-theme-antv/site/components/Search.tsx
- @antv/gatsby-theme-antv/site/global.less
- example/docs/specification/getting-started.zh.md
- yarn.lock
https://github.com/algolia/docsearch-configs/pull/1116
> feat: 🔍 support search of algolia

- @antv/gatsby-theme-antv/site/common.json
- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Banner.tsx
- @antv/gatsby-theme-antv/site/components/Notification.module.less
- @antv/gatsby-theme-antv/site/components/Notification.tsx
- example/site/pages/index.zh.tsx
> refactor: Notification

- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Banner.tsx
- @antv/gatsby-theme-antv/site/components/Features.tsx
- example/site/pages/index.zh.tsx
closes antvis/antvis.github.io#35
> fix: anchor router

- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Banner.tsx
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/components/Products.tsx
- @antv/gatsby-theme-antv/site/global.less
简化了代码，使用了 https://developer.mozilla.org/zh-CN/docs/Web/CSS/scroll-behavior
> feat: improve button scroll behavior and simplify code

- @antv/gatsby-theme-antv/README.md
- @antv/gatsby-theme-antv/gatsby-node.js
- README.md
https://github.com/antvis/gatsby-theme-antv/issues/65
> feat: add codeSplit option

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/components/Search.tsx
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
> feat: Add docsearchOptions to theme options

- .eslintrc
- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/jest.setup.js
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
close https://github.com/antvis/gatsby-theme-antv/issues/71
解决 locale.json 修改后需要重启 gatsby 服务才能生效的问题。
> refactor: i18n resources

- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Banner.tsx
- @antv/gatsby-theme-antv/site/components/Features.module.less
- example/site/pages/index.zh.tsx
- yarn.lock
fix: the min-width and padding of the button to fit the long text.
> Button width

- @antv/gatsby-theme-antv/gatsby-browser.js
- @antv/gatsby-theme-antv/site/components/Footer.tsx
- @antv/gatsby-theme-antv/site/components/Header.tsx
- example/site/pages/index.zh.tsx
> feat: Add PWA update notification

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
修复底部上一篇下一篇的顺序问题。
@antvis/developers
> fix: prev and next order

- @antv/gatsby-theme-antv/README.md
- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/site/components/Banner.module.less
- @antv/gatsby-theme-antv/site/components/Cases.module.less
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Search.module.less
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
- README.md
- yarn.lock
> fix: 💄 use primary color in banner

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/NavigatorBanner.tsx
- @antv/gatsby-theme-antv/site/hooks.ts
- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
在前端实现上一页下一页，并进一步优化性能，节能低碳。
close #100
> refactor:  prev next navigator for better perf

- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
> fix: wrong active example in ssr

- @antv/gatsby-theme-antv/site/components/Companies.module.less
- @antv/gatsby-theme-antv/site/components/Features.module.less
> make primary color consistent

- @antv/gatsby-theme-antv/site/layouts/layout.tsx
> fix: locale jump issue

- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- example/package.json
> feat: ⚡ support monorepo edit url 

- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/getProducts.tsx
fix: url 404 problem on the bottom of the page.
> fix: url 404 problem on the bottom of the page.

- @antv/gatsby-theme-antv/site/components/Footer.tsx
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
- README.md
- example/gatsby-browser.js
> feat: allow custom footer

- .github/workflows/preview.yml
- package.json
https://github.com/marketplace/actions/surge-pr-preview
> feat: add surge-preview

- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
1. fix the overflow code hinting
2. change the inactive selected background for the editor
> fix: fix the overflow widget

- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
change api-extractor exception to warning level
> fix: change api-extractor exception to warning level

- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- example/examples/category/second/demo/basic.js
- example/examples/second/demo/basic.js
- example/gatsby-browser.js
> fix: fix demo to support react

- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- example/examples/basic/demo/basic.jsx
Change the position of the replace insertCss
> fix: fix the bug of multiple annotations

- example/package.json
- yarn.lock
可以了：https://antvis-gatsby-theme-antv-preview-pr-220.surge.sh/zh/docs/other/category/test1
> fix: workspace version not matched

- @antv/gatsby-theme-antv/gatsby-config.js
- README.md
- example/docs/other/category/test1.en.md
- example/docs/other/category/test1.zh.md
new demand：embed files from other directory
> feat: support cross-directory embed

- @antv/gatsby-theme-antv/site/components/PlayGround.module.less
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- @antv/gatsby-theme-antv/site/global.d.ts
- @antv/gatsby-theme-antv/site/templates/document.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
Fix bugs in version 1.0.0 beta.10:
* Hide breadcrumbName in mobile view.
* Fix the skeleton loading condition of the code editor.
* Allow the state of API navigation to change with the page scrolling.
> 1.0.0 beta.10 fix

- .github/workflows/preview.yml
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
https://github.com/antvis/antvis.github.io/pull/85#issuecomment-723432266
> fix: surge-preview

- @antv/gatsby-theme-antv/site/components/LayoutIcons.tsx
- @antv/gatsby-theme-antv/site/components/LayoutSwitcher.module.less
- @antv/gatsby-theme-antv/site/components/LayoutSwitcher.tsx
> style(💄): tweak layout switcher style

- @antv/gatsby-theme-antv/site/components/APIDoc.module.less
- @antv/gatsby-theme-antv/site/components/APIDoc.tsx
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- @antv/gatsby-theme-antv/site/components/Tabs.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- README.md
- yarn.lock
* Change the layout  of gallery and example to support AntV new site
> feat: tweak layout of example for antv home site

- @antv/gatsby-theme-antv/site/components/Article.module.less
- @antv/gatsby-theme-antv/site/components/Product.module.less
> style: fix Header products card style

- @antv/gatsby-theme-antv/site/components/Footer.module.less
- @antv/gatsby-theme-antv/site/components/Footer.tsx
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Product.module.less
- example/gatsby-browser.js
> fix: header and footer style

- @antv/gatsby-theme-antv/site/common.json
- @antv/gatsby-theme-antv/site/components/APIDoc.module.less
- @antv/gatsby-theme-antv/site/components/PlayGround.module.less
- @antv/gatsby-theme-antv/site/components/Tabs.module.less
- @antv/gatsby-theme-antv/site/components/ThemeSwitcher.module.less
- @antv/gatsby-theme-antv/site/components/getProducts.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- example/docs/specification/test-only-cn.md
* demo页面视图切换卡片垂直居中对齐
* 将demo页面结构从Article中抽出
* 修改AVAheader文案
> fix: demo 页面优化

- @antv/gatsby-theme-antv/site/components/getProducts.tsx
> fix: product_info

- @antv/gatsby-theme-antv/site/components/APIDoc.tsx
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/components/getProducts.tsx
* 修复官hover网首页所有产品tab闪烁
* 图表详情页面没有API文档时优先展示设计文档
> fix: 修复官hover网首页所有产品tab闪烁问题

- @antv/gatsby-theme-antv/site/components/Footer.tsx
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
- example/examples/basic/index.en.md
https://github.com/antvis/G2Plot/issues/2031
> fix: footer with menu in gallary page

- @antv/gatsby-theme-antv/site/templates/markdown.module.less
> fix: change anchor-ink-ball style

- @antv/gatsby-theme-antv/site/components/APIDoc.tsx
- @antv/gatsby-theme-antv/site/components/MdPlayground.tsx
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
* Add English comment to auto-comment of insertCss.
* Use the default collapse icon for a better experience.
> fix: solve some issue of version 1.0.7

- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/getProducts.tsx
- @antv/gatsby-theme-antv/site/templates/markdown.module.less
- yarn.lock
upgrade gatsby to fix ssr issue
https://github.com/gatsbyjs/gatsby/issues/29326
> chore: upgrade gatsby version

- @antv/gatsby-theme-antv/site/components/Header.tsx
> fix: add ChinaMirror url for antv home site

- @antv/gatsby-theme-antv/site/components/Footer.tsx
> chore: remove yunfengdie from site footer

- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Header.tsx
> style: perf menu hover

- @antv/gatsby-theme-antv/site/components/ThemeSwitcher.tsx
> chore: adjust theme url

- @antv/gatsby-theme-antv/site/components/Search.tsx
> fix: transform searched x6 sites url

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/jest.config.js
- @antv/gatsby-theme-antv/package.json
- @antv/gatsby-theme-antv/site/components/Announcement.tsx
- @antv/gatsby-theme-antv/site/components/Contributors.tsx
- @antv/gatsby-theme-antv/site/components/Header.module.less
- @antv/gatsby-theme-antv/site/components/Header.tsx
- @antv/gatsby-theme-antv/site/components/MdPlayground.tsx
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- @antv/gatsby-theme-antv/site/components/TopBanner.tsx
- @antv/gatsby-theme-antv/site/layouts/layout.tsx
- @antv/gatsby-theme-antv/site/templates/example.tsx
- README.md
- example/gatsby-browser.js
- yarn.lock
在 `gatsby-config.js` 配置文件中添加  `showGithubStar` 选项：
```
siteMetadata: {
showGithubStar: true,  // 显示 github star
showGithubCorner: false, // 隐藏 github 图标
}
```
效果如下
> feat: 在 header 中显示 github star

- @antv/gatsby-theme-antv/gatsby-node.js
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/123920409-7da35c80-d9b8-11eb-8e7c-1dc003aed7c1.png)|![image](https://user-images.githubusercontent.com/15646325/123920364-73815e00-d9b8-11eb-9c97-1015416a68e2.png)|
> feat: 提升 createPages 的性能

- @antv/gatsby-theme-antv/gatsby-node.js
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
> fix: 改进传递过来的context数据，修改 图表示例中的编辑器的布局错误问题

- @antv/gatsby-theme-antv/gatsby-node.js
> fix: 修复gatsby-node.js 中的 变量缺少s结尾的bug

- @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
> feat: 侧边栏菜单切换的时候，不直接刷新页面 - 提升交互体验

- @antv/gatsby-theme-antv/site/components/PlayGround.module.less
- @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
- @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
| Before | After |
| --- | --- |
|![image](https://user-images.githubusercontent.com/15646325/124342489-f68ff780-dbf6-11eb-8191-34a42654e268.png) |![image](https://user-images.githubusercontent.com/15646325/124342477-dfe9a080-dbf6-11eb-9c59-6f07dafb68d4.png)|
|![image](https://user-images.githubusercontent.com/15646325/124342937-6784de80-dbfa-11eb-89b2-3ad26095ad47.png)|![image](https://user-images.githubusercontent.com/15646325/124342961-90a56f00-dbfa-11eb-95e1-9dde13f372dd.png)|
> style: 样式优化

- @antv/gatsby-theme-antv/README.md
- @antv/gatsby-theme-antv/gatsby-config.js
- @antv/gatsby-theme-antv/site/components/PlayGround.tsx
- @antv/gatsby-theme-antv/site/components/PlayGrounds.module.less
- @antv/gatsby-theme-antv/site/components/PlayGrounds.tsx
- README.md
- `无图片时`
- ` showExampleDemoTitle, 有截图的是否要展示 title 名称`
**false**
**true**
> feat: 添加 无图片的时候的title

- @antv/gatsby-theme-antv/gatsby-node.js
> fix: 修复文件过大时示例和文档丢失

- @antv/gatsby-theme-antv/site/components/getProducts.tsx
> fix(links): 修复国内镜像 link 处理
